name: hyphlow_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - hyphy
  - pandas
  - biopython
  - xlsxwriter
  - rapidfuzz
  - pyqt
  - pip
  - pip:
    - ete3
    - taxopy
    - qtawesome
